# -*- coding: utf-8 -*-
from abc import ABCMeta


class Info(metaclass = ABCMeta):
	"""
	Actual Minecraft: PE protocol version
	"""

	CURRENT_PROTOCOL = 107

	ACCEPTED_PROTOCOLS = [105, 106, 107]

	LOGIN_PACKET = 0x01

	PLAY_STATUS_PACKET = 0x02

	SERVER_TO_CLIENT_HANDSHAKE_PACKET = 0x03

	CLIENT_TO_SERVER_HANDSHAKE_PACKET = 0x04

	DISCONNECT_PACKET = 0x05

	BATCH_PACKET = 0x06

	RESOURCE_PACKS_INFO_PACKET = 0x07

	RESOURCE_PACK_STACK_PACKET = 0x08

	RESOURCE_PACK_CLIENT_RESPONSE_PACKET = 0x09

	TEXT_PACKET = 0x0a

	SET_TIME_PACKET = 0x0b

	START_GAME_PACKET = 0x0c

	ADD_PLAYER_PACKET = 0x0d

	ADD_ENTITY_PACKET = 0x0e

	REMOVE_ENTITY_PACKET = 0x0f

	ADD_ITEM_ENTITY_PACKET = 0x10

	ADD_HANGING_ENTITY_PACKET = 0x11

	TAKE_ITEM_ENTITY_PACKET = 0x12

	MOVE_ENTITY_PACKET = 0x13

	MOVE_PLAYER_PACKET = 0x14

	RIDER_JUMP_PACKET = 0x15

	REMOVE_BLOCK_PACKET = 0x16

	UPDATE_BLOCK_PACKET = 0x17

	ADD_PAINTING_PACKET = 0x18

	EXPLODE_PACKET = 0x19

	LEVEL_SOUND_EVENT_PACKET = 0x1a

	LEVEL_EVENT_PACKET = 0x1b

	BLOCK_EVENT_PACKET = 0x1c

	ENTITY_EVENT_PACKET = 0x1d

	MOB_EFFECT_PACKET = 0x1e

	UPDATE_ATTRIBUTES_PACKET = 0x1f

	MOB_EQUIPMENT_PACKET = 0x20

	MOB_ARMOR_EQUIPMENT_PACKET = 0x21

	INTERACT_PACKET = 0x22

	BLOCK_PICK_REQUEST_PACKET = 0x23

	USE_ITEM_PACKET = 0x24

	PLAYER_ACTION_PACKET = 0x25

	PLAYER_FALL_PACKET = 0x26

	HURT_ARMOR_PACKET = 0x27

	SET_ENTITY_DATA_PACKET = 0x28

	SET_ENTITY_MOTION_PACKET = 0x29

	SET_ENTITY_LINK_PACKET = 0x2a

	SET_HEALTH_PACKET = 0x2b

	SET_SPAWN_POSITION_PACKET = 0x2c

	ANIMATE_PACKET = 0x2d

	RESPAWN_PACKET = 0x2e

	DROP_ITEM_PACKET = 0x2f

	INVENTORY_ACTION_PACKET = 0x30

	CONTAINER_OPEN_PACKET = 0x31

	CONTAINER_CLOSE_PACKET = 0x32

	CONTAINER_SET_SLOT_PACKET = 0x33

	CONTAINER_SET_DATA_PACKET = 0x34

	CONTAINER_SET_CONTENT_PACKET = 0x35

	CRAFTING_DATA_PACKET = 0x36

	CRAFTING_EVENT_PACKET = 0x37

	ADVENTURE_SETTINGS_PACKET = 0x38

	BLOCK_ENTITY_DATA_PACKET = 0x39

	PLAYER_INPUT_PACKET = 0x3a

	FULL_CHUNK_DATA_PACKET = 0x3b

	SET_COMMANDS_ENABLED_PACKET = 0x3c

	SET_DIFFICULTY_PACKET = 0x3d

	CHANGE_DIMENSION_PACKET = 0x3e

	SET_PLAYER_GAME_TYPE_PACKET = 0x3f

	PLAYER_LIST_PACKET = 0x40

	EVENT_PACKET = 0x41

	SPAWN_EXPERIENCE_ORB_PACKET = 0x42

	CLIENTBOUND_MAP_ITEM_DATA_PACKET = 0x43

	MAP_INFO_REQUEST_PACKET = 0x44

	REQUEST_CHUNK_RADIUS_PACKET = 0x45

	CHUNK_RADIUS_UPDATED_PACKET = 0x46

	ITEM_FRAME_DROP_ITEM_PACKET = 0x47

	REPLACE_ITEM_IN_SLOT_PACKET = 0x48

	GAME_RULES_CHANGED_PACKET = 0x49

	CAMERA_PACKET = 0x4a

	ADD_ITEM_PACKET = 0x4b

	BOSS_EVENT_PACKET = 0x4c

	SHOW_CREDITS_PACKET = 0x4d

	AVAILABLE_COMMANDS_PACKET = 0x4e

	COMMAND_STEP_PACKET = 0x4f

	COMMAND_BLOCK_UPDATE_PACKET = 0x50

	UPDATE_TRADE_PACKET = 0x51

	RESOURCE_PACK_DATA_INFO_PACKET = 0x52

	RESOURCE_PACK_CHUNK_DATA_PACKET = 0x53

	RESOURCE_PACK_CHUNK_REQUEST_PACKET = 0x54

	TRANSFER_PACKET = 0x55

	PLAY_SOUND_PACKET = 0x56

	STOP_SOUND_PACKET = 0x57

	SET_TITLE_PACKET = 0x58
